#!/bin/zsh

alias g="git"
alias ions="npm run ionic:serve"
alias iond="npm run ionic:serve:dev"
alias rmnm="rm -rf node_modules"
alias rmnmi="rm -rf node_modules && npm i"
alias rmnmn="rmnmi && node install.dev.js"
alias rmnmnr="rmnmin && node recompile.js"
alias gc="cd ~/mercator-sdk-ui && git clean -xdf && cd orderapi-ui/mercator-sdk &&  rmnmn"
alias gcr="gc && node recompile.js"

case `uname -a` in
  *Linux*)
    alias unsafe-chrome='chromium-browser --disable-web-security';
    alias tmux="tmux -2";
    alias ack='ack-grep';
    alias v="vim";
    alias ls='ls --color=auto';;
  *Darwin*)
    alias unsafe-chrome='open /Applications/Google\ Chrome.app --args --disable-web-security';
    alias tmux="tmux -2 -u";
    alias vim="mvim -v"
    # what?
    ;;
esac

alias ll='ls -la'
