#!/bin/zsh
alias v="nvim"
alias npmrc="nvim ~/.npmrc"

alias sdk="~/mercator-sdk-ui/accelya-sdk"
alias adm="~/apps/IndustrySolutions/ADM-KPI-App"
alias nfe="~/NFE/frontend"

alias build_sdk="~/mercator-ui-sdk/scripts && bash ./buildSdk"
alias test_sdk="~/mercator-ui-sdk/scripts && bash ./unittestSdk"

alias hmr="npm run hmr"
alias npms="npm start"
alias strd="npm run start:training:dev"
alias npmt="npm run test:headless"

alias rmnm="rm -rf node_modules"

alias bm="npm run build-modules"
alias bma="npm run build-modules:async"

alias g="git"
alias gc="git clean -xdf"
alias ea="nvim ~/.aliases";
alias ryl="rm yarn.lock";

alias d="docker"

alias chrome-no-security="killall 'Google Chrome'; open -n -a /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --args --user-data-dir='/tmp/chrome_dev_test' --disable-web-security";

alias ...="../../"
alias ....="../../../"

case `uname -a` in
  *Linux*)
    alias unsafe-chrome='chromium-browser --disable-web-security';
    alias tmux="tmux -2";
    alias ack='ack-grep';
    alias v="vim";
    alias ls='ls --color=auto';;
  *Darwin*)
    alias unsafe-chrome='open /Applications/Google\ Chrome.app --args --disable-web-security';
    # alias tmux="tmux -2 -u";
    # alias vim="mvim -v"
    # what?
    ;;
esac

alias ll='ls -la'
